language: cpp
sudo: false

matrix:
  include:
    #==============================
    #
    #          osx g++ 
    #
    #==============================

    - os: osx
      osx_image: xcode7.3
      compiler: g++

    - os: osx
      osx_image: xcode8
      compiler: g++

    - os: osx
      osx_image: xcode8.3
      compiler: g++

    - os: osx
      osx_image: xcode9
      compiler: g++

    - os: osx
      osx_image: xcode9.1
      compiler: g++

    - os: osx
      osx_image: xcode9.2
      compiler: g++

    - os: osx
      osx_image: xcode9.3
      compiler: g++

    - os: osx
      osx_image: xcode9.4
      compiler: g++

    - os: osx
      osx_image: xcode10
      compiler: g++

    #==============================
    #
    #          linux g++
    #
    #==============================
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      compiler: g++

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      compiler: g++

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      compiler: g++

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      compiler: g++

before_install:
  - eval
  - cd ${TRAVIS_BUILD_DIR}  
  - git clone https://github.com/EASEA/easea.git
  - cd easea/
  - git checkout v1.0.3
  - if [ $TRAVIS_OS_NAME = "osx" ]; then
      cd libeasea;
      sed -i -e "s/-fopenmp//g" Makefile;
    fi;
  

install:
  - cd ${TRAVIS_BUILD_DIR}/easea
  - make
  - ./install.sh local
  - export EZ_PATH=${TRAVIS_BUILD_DIR}/easea/

before_script:
  - cd ${TRAVIS_BUILD_DIR}  
  - ./easea/bin/easea schedules.ez
  - chmod 777 ./hack.sh
  - ./hack.sh
  - if [ $TRAVIS_OS_NAME = "osx" ]; then
      sed -i -e "s/-fopenmp//g" Makefile;
    fi;

script:
  - make

after_script:
  - make clean